language: python
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - sudo apt-get -y install fluidsynth
  - pip install -e .[test,optional,schema]
script:
  - pytest --cov="muspy/" tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
