language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U --upgrade pip
  - pip install -U --upgrade pytest
  - pip install -U --upgrade pytest-cov
install:
  - pip install -e .[test,optional,schema]
script:
  - pytest --cov="muspy/" tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
